/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pakage1;

import config.dbconfig;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import static pakage1.Admin.date;
import java.awt.print.*;
import java.text.MessageFormat;



/**
 *
 * @author zanec
 */
public class patientList extends javax.swing.JFrame {

    /**
     * Creates new form User
     */
    public patientList() {
        //this.jdate = jdate.getDate();
        initComponents();
        displayData();
         patienttable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
         TableColumnModel columnModel =  patienttable.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(10);
        ImageIcon icon2= new ImageIcon(getClass().getResource("arrow2.png"));
         Image img2= icon2.getImage().getScaledInstance(arrows.getWidth(), arrows.getHeight(), Image.SCALE_SMOOTH);
         arrows.setIcon(new ImageIcon(img2));          
    }
    public void displayData(){
       
        try{
       
            dbconfig dbc = new dbconfig();
            ResultSet rs = dbc.getData("SELECT * FROM tbl_patient");
            patienttable.setModel(DbUtils.resultSetToTableModel(rs));
            DefaultTableModel model = (DefaultTableModel)patienttable.getModel();
            
              String[] columnIdentifiers = {"ID", "LastName", "FirstName", "MiddleName", "Gender", "Status", ""
                    + "Email", "Address", "Contact","Date", "Time","Remarks" };
             model.setColumnIdentifiers(columnIdentifiers);
             rs.close();
        }catch(SQLException ex){
            System.out.println("Error Message: "+ex);    
        } 
    }
        public void reset(){
        id.setText("");
        lastname.setText("");
        firstname.setText("");
        middle.setText("");
        gender.clearSelection();
        status.setSelectedIndex(0);
        address.setText("");
        email.setText("");
        contact.setText("");
        //date.setText("");
        time.setText("");
        remark.setText("");
        
         jdate.setDate(null);
        
        
     
    }
        

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        gender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        arrows = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        next = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        patienttable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        middle = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        insert = new javax.swing.JButton();
        update = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        remark = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        print = new javax.swing.JButton();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        status = new javax.swing.JComboBox<>();
        text = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jdate = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        clear1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setFocusable(false);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(183, 30, 30));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PATIENT APPOINTMENT LIST");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 50));

        arrows.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pakage1/arrow2.png"))); // NOI18N
        arrows.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arrowsMouseClicked(evt);
            }
        });
        jPanel2.add(arrows, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 37, 31));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("X");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 40, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("__");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 40, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        next.setBackground(new java.awt.Color(255, 255, 255));
        next.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        next.setForeground(new java.awt.Color(183, 30, 30));
        next.setText("BOOK APPOINTMENT");
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextMouseExited(evt);
            }
        });
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel3.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, -1, 30));

        patienttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patienttableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(patienttable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 860, 150));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Contact:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 80, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Lastname:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 80, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("First Name:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 80, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Middle Initial:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 80, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Address:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 80, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Email:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 80, 30));

        contact.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel3.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 310, 30));

        lastname.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        jPanel3.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 310, 30));

        firstname.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel3.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 310, 30));

        middle.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel3.add(middle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 310, 30));

        email.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 310, 30));

        insert.setBackground(new java.awt.Color(255, 255, 255));
        insert.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        insert.setForeground(new java.awt.Color(183, 30, 30));
        insert.setText("INSERT");
        insert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                insertMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                insertMouseExited(evt);
            }
        });
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        jPanel3.add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 98, 30));

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(183, 30, 30));
        update.setText("UPDATE");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel3.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 100, 30));

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        clear.setForeground(new java.awt.Color(183, 30, 30));
        clear.setText("CLEAR");
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
        });
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel3.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 100, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Gender:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 80, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Status");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 80, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Date:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 80, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Time:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 80, 30));

        time.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel3.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 310, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Remark:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 80, 30));

        remark.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel3.add(remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 310, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("ID:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 80, 30));

        id.setEditable(false);
        id.setBackground(new java.awt.Color(255, 255, 255));
        id.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        id.setEnabled(false);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 310, 30));

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(183, 30, 30));
        delete.setText("DELETE");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel3.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 98, 30));

        address.setColumns(20);
        address.setRows(5);
        jScrollPane2.setViewportView(address);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 310, 70));

        print.setBackground(new java.awt.Color(255, 255, 255));
        print.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        print.setForeground(new java.awt.Color(183, 30, 30));
        print.setText("PRINT");
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printMouseExited(evt);
            }
        });
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel3.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 100, 30));

        male.setBackground(new java.awt.Color(255, 255, 255));
        gender.add(male);
        male.setText("Male");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, male, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), male, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jPanel3.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 70, 30));

        female.setBackground(new java.awt.Color(255, 255, 255));
        gender.add(female);
        female.setText("Female");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, female, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), female, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jPanel3.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 80, 30));

        status.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Engaged", "Married", "Widow" }));
        jPanel3.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 310, 30));
        jPanel3.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 260, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 150, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("ALL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 150, 30));
        jPanel3.add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 310, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Male", "Female" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 30));

        clear1.setBackground(new java.awt.Color(255, 255, 255));
        clear1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        clear1.setForeground(new java.awt.Color(183, 30, 30));
        clear1.setText("REFRESH");
        clear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clear1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clear1MouseExited(evt);
            }
        });
        clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear1ActionPerformed(evt);
            }
        });
        jPanel3.add(clear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 100, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
    User us = new User();
    us.setVisible(true);
    }//GEN-LAST:event_nextActionPerformed

    private void nextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseEntered
        // TODO add your handling code here:
        next.setBackground(new Color(183,30,30));
        next.setForeground(Color.WHITE);
    }//GEN-LAST:event_nextMouseEntered

    private void nextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseExited
        // TODO add your handling code here:
         next.setBackground(new Color(255,255,255));
        next.setForeground(new Color(183,30,30));
    }//GEN-LAST:event_nextMouseExited

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void insertMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_insertMouseEntered

    private void insertMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_insertMouseExited

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        String date1  = ((JTextField)jdate.getDateEditor().getUiComponent()).getText();
        if (lastname.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please type your Lastname!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(firstname.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please type your Firstname", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }else if (middle.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please type your Middle Name!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(gender.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Please select your Gender!", "Error", JOptionPane.ERROR_MESSAGE);
            return;      
        }else if(status.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select your Status!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(email.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please type your Email!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(address.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please type your Address!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(contact.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please type your Contact!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(jdate.getDate()==null) {
            JOptionPane.showMessageDialog(this, "Please type the Date!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(time.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please type the Time!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(remark.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please type the Remark!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        
        dbconfig dbc = new dbconfig();
        dbc.insertData("INSERT INTO tbl_patient (p_lastname, p_firstname, p_middle, p_gender, p_status, p_email, p_address, p_contact, p_date, p_time, p_remark) "
                + "VALUES ('"+lastname.getText()+"', '"+firstname.getText()+"','"+middle.getText()+"','"+gender.getSelection().getActionCommand()+"','"+status.getSelectedItem().toString()+"','"+email.getText()+"','"+address.getText()+"','"+contact.getText()+"','"+jdate+"','"+time.getText()+"','"+remark.getText()+"')");       
        displayData();
        reset();
    }//GEN-LAST:event_insertActionPerformed

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_updateMouseExited

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try{ 
        int rowIndex = patienttable.getSelectedRow();
            if(rowIndex < 0){
                JOptionPane.showMessageDialog(null, "Please Select an Item!");
            }else{
        
        String date1  = ((JTextField)jdate.getDateEditor().getUiComponent()).getText();
        dbconfig dbc = new dbconfig();
        int num = dbc.updateData("UPDATE tbl_patient "
                + "SET p_lastname = '"+lastname.getText()+"', p_firstname='"+firstname.getText()+"', "
                        + "p_middle ='"+middle.getText()+"', p_gender='"+gender.getSelection().getActionCommand()+"',p_status='"+status.getSelectedItem().toString()+ "',p_email='"+email.getText()+ "',p_address='"+address.getText()+ "',p_contact='"+contact.getText()+"',p_date='"+jdate+"',p_time='"
                                +time.getText()+"',p_remark='"+remark.getText()+"'"
                                + "WHERE p_id = '"+id.getText()+"'");
       
        if(num == 0){
           
        }else{
           JOptionPane.showMessageDialog(null, "Updated Successfully!");
           displayData();
           reset();
        } }
             } catch (Exception e) {
            Logger.getLogger(patientList.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_clearMouseEntered

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_clearMouseExited

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        reset();
    }//GEN-LAST:event_clearActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseExited

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int rowIndex = patienttable.getSelectedRow();
       if(rowIndex < 0){
           JOptionPane.showMessageDialog(null, "Please select a data first");
       }else{
            TableModel model = patienttable.getModel();
            Object value = model.getValueAt(rowIndex, 0);
            String id = value.toString();
              int a=JOptionPane.showConfirmDialog(null,"Are you sure to delete ID: " +id+" ?");
                    if(a==JOptionPane.YES_OPTION){  
                            dbconfig dbc = new dbconfig();
                               int r_id = Integer.parseInt(id);
                dbc.deleteData(Integer.parseInt(id));
                            displayData();
                            reset();
                    }    
       }
    }//GEN-LAST:event_deleteActionPerformed

    private void patienttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patienttableMouseClicked
       int rowIndex = patienttable.getSelectedRow();
        if(rowIndex < 0){
            
        }else{
            TableModel model = patienttable.getModel();
            id.setText(""+model.getValueAt(rowIndex,0));
            lastname.setText(""+model.getValueAt(rowIndex,1));
            firstname.setText(""+model.getValueAt(rowIndex,2));
            middle.setText(""+model.getValueAt(rowIndex,3));
           String rb = model.getValueAt(rowIndex, 4).toString();
                        switch(rb){
                            case "Male":
                                male.setSelected(true);
                                break;
                            default:
                                female.setSelected(true);
                                break;
                        }
              String cb = model.getValueAt(rowIndex, 5).toString();
                        if(cb.equals("Single")){
                           status.setSelectedIndex(0);
                        }else if(cb.equals("Engaged")){
                           status.setSelectedIndex(1);
                        }
                        else if(cb.equals("Married")){
                          status.setSelectedIndex(2);
                        }else{
                           status.setSelectedIndex(3);
                        }
            email.setText(""+model.getValueAt(rowIndex,6));
            address.setText(""+model.getValueAt(rowIndex,7));
            contact.setText(""+model.getValueAt(rowIndex,8));
            String dateString = model.getValueAt(rowIndex, 9).toString();
            time.setText(""+model.getValueAt(rowIndex,10));
            remark.setText(""+model.getValueAt(rowIndex,11));
        }
        
    }//GEN-LAST:event_patienttableMouseClicked

    private void arrowsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowsMouseClicked
        Admin ad = new Admin();
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_arrowsMouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        int a=JOptionPane.showConfirmDialog(null, "Confirm Exit?");
        if(a==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_printMouseEntered

    private void printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_printMouseExited

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
    
       
     try {
        MessageFormat header = new MessageFormat("Patient Table");
        MessageFormat footer = new MessageFormat("Page {0}");
        patienttable.print(JTable.PrintMode.FIT_WIDTH, header, footer);
    } catch (PrinterException e) {
        JOptionPane.showMessageDialog(null, "Cannot print table: " + e.getMessage());
    }
    
    
/*printPage pp = new printPage();
int selectedRow = patienttable.getSelectedRow();

    if (selectedRow != -1) {
        try {
            DefaultTableModel model = (DefaultTableModel) patienttable.getModel();
            int columnCount = model.getColumnCount();
            StringBuilder rowData = new StringBuilder();

            // Append data for selected row
            String[] columnHeaders = {"ID", "Last Name", "First Name", "Middle Name", "Gender", "Status", ""
                    + "Email", "Address", "Contact","Date", "Time","Remarks" };
            String[] rowDataValues = new String[columnCount];

            for (int column = 0; column < columnCount; column++) {
                rowDataValues[column] = model.getValueAt(selectedRow, column).toString();
            }

            String header = "            \t\tMEDICAL APPOINTMENT\n\n";

            String details = "Patient Details:\n\n\n";
            rowData.append(header);
            rowData.append(details);

            for (int i = 0; i < columnHeaders.length; i++) {
                rowData.append(columnHeaders[i]).append(": ").append(rowDataValues[i]).append("\n");
                rowData.append("\n"); // Add spacing after each detail
            }
            pp.setVisible(true);
            pp.area1.setText(rowData.toString());

            // Center align the text in the JTextArea
            pp.area1.setAlignmentX(Component.CENTER_ALIGNMENT);
            pp.area1.setAlignmentY(Component.CENTER_ALIGNMENT);

            // Set the font style and size
            Font font = new Font("Times New Roman", Font.PLAIN, 13);
            pp.area1.setFont(font);
            this.dispose();
            // Print the JTextArea content
           // pp.area1.print();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    } else {
        JOptionPane.showMessageDialog(null, "No row selected.");
    }*/
   
    }//GEN-LAST:event_printActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       DefaultTableModel model = (DefaultTableModel)patienttable .getModel();
    TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
    patienttable.setRowSorter(tr);
    
    String selectedMajor = text.getText().trim();
    tr.setRowFilter(RowFilter.regexFilter(selectedMajor));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       text.setText("");
    DefaultTableModel model = (DefaultTableModel)patienttable .getModel();
    TableRowSorter<DefaultTableModel> tr = (TableRowSorter<DefaultTableModel>) patienttable.getRowSorter();

    if (tr != null && tr.getRowFilter() != null) {
        tr.setRowFilter(null); // Remove the existing row filter
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       DefaultTableModel model = (DefaultTableModel) patienttable.getModel();
    TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
    patienttable.setRowSorter(tr);
    
    String selectedMajor = jComboBox1.getSelectedItem().toString().trim();
    tr.setRowFilter(RowFilter.regexFilter(selectedMajor));
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void clear1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_clear1MouseEntered

    private void clear1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_clear1MouseExited

    private void clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear1ActionPerformed
       DefaultTableModel model = (DefaultTableModel) patienttable.getModel();
    TableRowSorter<DefaultTableModel> tr = (TableRowSorter<DefaultTableModel>) patienttable.getRowSorter();

    if (tr != null && tr.getRowFilter() != null) {
        tr.setRowFilter(null); // Remove the existing row filter
    }
    
    model.fireTableDataChanged();
    }//GEN-LAST:event_clear1ActionPerformed

public static void AddRowToJTable(Object[] dataRow){
           DefaultTableModel model = (DefaultTableModel)patienttable.getModel();
           model.addRow(dataRow);
       }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patientList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patientList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patientList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patientList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patientList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JLabel arrows;
    private javax.swing.JButton clear;
    private javax.swing.JButton clear1;
    private javax.swing.JTextField contact;
    private javax.swing.JButton delete;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField firstname;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JTextField id;
    private javax.swing.JButton insert;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JTextField lastname;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField middle;
    private javax.swing.JButton next;
    public static javax.swing.JTable patienttable;
    private javax.swing.JButton print;
    private javax.swing.JTextField remark;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTextField text;
    private javax.swing.JTextField time;
    private javax.swing.JButton update;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
